apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all
  namespace: test-manager
spec:
  podSelector:
    matchLabels:
  ingress:
  - {}
  egress:
  - {}
  policyTypes:
  - Ingress
  - Egress
